// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Optimal
{
    [Table("empdet", Schema = "huresy")]
    public partial class empdet
    {
        public empdet()
        {
            leaveoperation = new HashSet<leaveoperation>();
        }

        [Key]
        public int empid { get; set; }
        [StringLength(20)]
        public string title { get; set; }
        [Required]
        [StringLength(50)]
        public string surname { get; set; }
        [Required]
        [StringLength(100)]
        public string othernames { get; set; }
        public int? maritalcode { get; set; }
        [Required]
        [StringLength(10)]
        public string gender { get; set; }
        public int? countrycode { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? birthdate { get; set; }
        [Column(TypeName = "image")]
        public byte[] empphoto { get; set; }
        [StringLength(25)]
        public string idno { get; set; }
        [StringLength(25)]
        public string ppno { get; set; }
        [StringLength(25)]
        public string pin { get; set; }
        [StringLength(25)]
        public string nssf { get; set; }
        [StringLength(25)]
        public string nhif { get; set; }
        [StringLength(30)]
        public string prevempid { get; set; }
        public bool issupervisor { get; set; }
        public int? supervisorempid { get; set; }
        public int? fieldmanagerempid { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? empdate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? releasedate { get; set; }
        public int? probationperiod { get; set; }
        public bool confirmed { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? confirmdate { get; set; }
        public int toscode { get; set; }
        public int empstatecode { get; set; }
        public int empservicestatecode { get; set; }
        [Required]
        [StringLength(15)]
        public string emplevelcode { get; set; }
        public int? leaveawardgroupcode { get; set; }
        public int deptid { get; set; }
        public int jobcode { get; set; }
        [Required]
        [StringLength(25)]
        public string taxtypecode { get; set; }
        [Required]
        [StringLength(255)]
        public string paygradecode { get; set; }
        public int? paynotch { get; set; }
        public int? paystep { get; set; }
        public int? paytypecode { get; set; }
        public int paypointcode { get; set; }
        [Required]
        [StringLength(15)]
        public string costareacode { get; set; }
        [StringLength(10)]
        public string currencysymbol { get; set; }
        public double? basicsalary { get; set; }
        public int payfrequencyid { get; set; }
        [StringLength(50)]
        public string residentialstatus { get; set; }
        [StringLength(50)]
        public string employeetype { get; set; }
        [StringLength(50)]
        public string housingtype { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? recorddate { get; set; }
        [StringLength(255)]
        public string currentpostaladdr { get; set; }
        public int? currentpostaltown { get; set; }
        [StringLength(255)]
        public string currentpostalcode { get; set; }
        public int? currentpostalcounty { get; set; }
        [StringLength(255)]
        public string officialemail { get; set; }
        [StringLength(255)]
        public string officialphone { get; set; }
        [StringLength(255)]
        public string officialmobile { get; set; }
        [StringLength(255)]
        public string permanentpostaladdr { get; set; }
        public int? permanentpostalTown { get; set; }
        [StringLength(255)]
        public string permanentpostalcode { get; set; }
        public int? permanenrpostalcountry { get; set; }
        [StringLength(255)]
        public string personalemail { get; set; }
        [StringLength(255)]
        public string permanentphone { get; set; }
        [StringLength(255)]
        public string residentialstreet { get; set; }
        public int? residentialtown { get; set; }
        public int? residentialcountry { get; set; }
        [Column(TypeName = "image")]
        public byte[] empsignature { get; set; }

        [ForeignKey(nameof(deptid))]
        [InverseProperty(nameof(department.empdet))]
        public virtual department dept { get; set; }
        [ForeignKey(nameof(emplevelcode))]
        [InverseProperty(nameof(emplevel.empdet))]
        public virtual emplevel emplevelcodeNavigation { get; set; }
        [ForeignKey(nameof(empservicestatecode))]
        [InverseProperty(nameof(empservicestate.empdet))]
        public virtual empservicestate empservicestatecodeNavigation { get; set; }
        [ForeignKey(nameof(jobcode))]
        [InverseProperty(nameof(job.empdet))]
        public virtual job jobcodeNavigation { get; set; }
        [InverseProperty("emp")]
        public virtual ICollection<leaveoperation> leaveoperation { get; set; }
    }
}