// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Optimal
{
    [Table("emplevel", Schema = "huresy")]
    public partial class emplevel
    {
        public emplevel()
        {
            empdet = new HashSet<empdet>();
        }

        [Key]
        [StringLength(15)]
        public string emplevelcode { get; set; }
        [StringLength(100)]
        public string empleveldesc { get; set; }
        public int? seniority { get; set; }
        [Required]
        public bool? emplevelvalid { get; set; }

        [InverseProperty("emplevelcodeNavigation")]
        public virtual ICollection<empdet> empdet { get; set; }
    }
}