// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Entities.Optimal
{
    [Table("job", Schema = "huresy")]
    public partial class job
    {
        public job()
        {
            empdet = new HashSet<empdet>();
        }

        [Key]
        public int jobid { get; set; }
        [StringLength(10)]
        public string shortcode { get; set; }
        [Required]
        [StringLength(100)]
        public string jobtitle { get; set; }
        [StringLength(1000)]
        public string jobdesc { get; set; }
        public int? minage { get; set; }
        public int? maxage { get; set; }
        public int? jobcatcode { get; set; }
        public int? reportsto { get; set; }
        [Required]
        public bool? jobvalid { get; set; }
        public int? reviewgroupid { get; set; }

        [InverseProperty("jobcodeNavigation")]
        public virtual ICollection<empdet> empdet { get; set; }
    }
}