// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Core.Entities.Optimal;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Infra.Optimal
{
    public partial class OptimalDbContext : DbContext
    {
        public OptimalDbContext()
        {
        }

        public OptimalDbContext(DbContextOptions<OptimalDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<empdet> empdet { get; set; }
        public virtual DbSet<emplevel> emplevel { get; set; }
        public virtual DbSet<empservicestate> empservicestate { get; set; }
        public virtual DbSet<empstate> empstate { get; set; }
        public virtual DbSet<job> job { get; set; }
        public virtual DbSet<leaveoperation> leaveoperation { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}